// <auto-generated />
using ApiMastery;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiMastery.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191112000355_TestSeedData")]
    partial class TestSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiMastery.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<int>("GameId");

                    b.Property<string>("Title");

                    b.HasKey("CommentId");

                    b.HasIndex("GameId");

                    b.ToTable("Comments");

                    b.HasData(
                        new { CommentId = 1, Body = "TestBody", GameId = 1, Title = "TestComment" }
                    );
                });

            modelBuilder.Entity("ApiMastery.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("SeriesId");

                    b.HasKey("GameId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Games");

                    b.HasData(
                        new { GameId = 1, Name = "TestGame", SeriesId = 1 }
                    );
                });

            modelBuilder.Entity("ApiMastery.Models.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("SeriesId");

                    b.ToTable("Series");

                    b.HasData(
                        new { SeriesId = 1, Name = "TestSeries" }
                    );
                });

            modelBuilder.Entity("ApiMastery.Models.Comment", b =>
                {
                    b.HasOne("ApiMastery.Models.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApiMastery.Models.Game", b =>
                {
                    b.HasOne("ApiMastery.Models.Series", "Series")
                        .WithMany("Games")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
